### ISSUE TITLE
Adam Roach BLOCK

### ISSUE THREAD

**Issue by jimsch** [cbor-wg/charter#5]
This is a "DISCUSS-discuss" style block, in the spirit of backing up and making sure we're making the right overall decision here.

I'd like us to have a short conversation about whether it makes sense for the CDDL work to continue in the CBOR working group. Given that it has been rescoped and renamed to be a more general-purpose schema language covering not just CBOR, but the much broader JSON universe, it seems that this work is extremely likely to have a broad constituency outside of those people who typically participate in working groups that focus on IoT use-cases. Keeping it part of CBOR does not seem to serve that community well.

Should we consider splitting the CDDL update and maintenance work off into a separate working group, rather than rechartering CBOR with the rather significant expansion considered in this charter proposal?

**Comment by cabo** [comment]
Adam yesterday: "Okay — I’m happy with the level of consideration that’s happened here. I merely wanted to ensure the possibility had been considered. I’ll clear."

So I think the DISCUSS discussion has happened and we can close this issue.

**Comment by fpalombini** [comment]
Agreed.
