### ISSUE TITLE
Mirja Block - text around fixing Internet standards

### ISSUE THREAD

**Issue by jimsch** [cbor-wg/charter#6]
1) First on this:
"After that, the CBOR working group will monitor issues found with the CBOR specification and, if needed, will produce an updated document." This intention seems to contradict the idea of an Internet Standard in RFC2026 a bit:
   "A specification for which significant implementation and successful
   operational experience has been obtained may be elevated to the
   Internet Standard level.  An Internet Standard (which may simply be
   referred to as a Standard) is characterized by a high degree of
   technical maturity and by a generally held belief that the specified
   protocol or service provides significant benefit to the Internet
   community."
Maybe this is nit-picking but if the group is not sure if there are further issue, one should probably simply not push for Internet Standard...

**Comment by fpalombini** [comment]
Remove the following sentence to fix this BLOCK: 

"After that, the CBOR working group will monitor issues found with the CBOR specification and, if needed, will produce an updated document."
